name: chess
version: '1.0-SNAPSHOT'
main: io.github.zeqky.chess.plugin.ChessPlugin
api-version: '1.21'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.2.0
  - org.jetbrains.kotlin:kotlin-reflect:2.2.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  - io.github.zeqky:fount-core:1.0.1
  - io.github.monun:heartbeat-coroutines:0.0.5
  - io.github.monun:invfx-core:3.3.2